logging:
  level:
    org.flowable.ui.modeler.rest.app: debug
    com.example.oldguy: debug
    org.springframework.transaction: debug
    com.zaxxer.hikari: debug

#    root: debug
server:
  port: 8088
  servlet:
    context-path: "/flowable-modeler-demo"
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/flowable-modeler-demo?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 15
  application:
    name: flowable-modeler-demo



mybatis-plus:
  type-aliases-package: com.example.oldguy.modules.app.dao.entities


flowable:
  app:
    enabled: false
  cmmn:
    enabled: false
  dmn:
    enabled: false
  form:
    enabled: false
  idm:
    enabled: false
  process-definition-location-prefix: "classpath*:/processes/rollback"